###*DEPLOYMENT AND SERVICE*####
###***DEPLOYMENT + SERVICE***###

apiVersion: apps/v1                         # API version for Deployment
kind: Deployment                            # Kubernetes resource type
metadata:
  name: nginx-deployment                    # Deployment name
  namespace: prod                            # Deployment created inside prod namespace
  labels:
    app: nginx                               # Deployment label
    env: prod                                # Environment label

spec:
  replicas: 2                                # Create 2 nginx Pods

  selector:
    matchLabels:
      app: nginx                              # Deployment manages Pods having app=nginx
      env: prod                               # Deployment manages Pods having env=prod

  template:
    metadata:
      labels:
        app: nginx                            # Pod label - must match selector
        env: prod                             # Pod label - must match selector
    spec:
      containers:
      - name: nginx-container                 # Container name
        image: nginx:latest                   # Nginx container image
        ports:
        - containerPort: 80                   # Nginx listens on port 80


---
###***SERVICE***###

apiVersion: v1                               # API version for Service
kind: Service                                # Kubernetes resource type
metadata:
  name: nginx-service                         # Service name
  namespace: prod                             # Service created inside prod namespace
  labels:
    app: nginx-service
    env: prod

spec:
  type: ClusterIP                             # Internal Kubernetes service

  selector:
    app: nginx                                # Select Pods having app=nginx
    env: prod                                 # Select Pods having env=prod

  ports:
  - name: http                                # Port name
    protocol: TCP                             # TCP protocol
    port: 80                                  # Service port
    targetPort: 80                            # Container port
